---
title: "Kaggle: House Prices with Advanced Regression Techniques"
authors: "Trevor Isaacson, Hawas Alsadeed, Evan Kessler"
date: "2/28/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Introduction
|   Imagine you're looking to purchase a home in the near future.  How do you know the price of that home is accurate and fair.  What factors or variables are you looking at to gauge the final price?  For many, home prices are a number associated with a few key variables.  For example, many buyers are looking at the number of bedrooms, bathrooms and the color of the fence.  What other things affect the price of a home?  Location, building materials, condition and quality are just a few that could potentially impact the price of a house.  In this Kaggle competition, we look at home prices in Ames, Iowa and over 80 variables associated with those homes.  





## Problem Discription
|   Can we accurately predict the price of a home?  




## Data Cleaning





## Multiple Linear Regression





## Splines and GAMs



















## Sources





