---
title: "Kaggle"
author: "Evan Kessler"
output: 
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
library(leaps)
library(ISLR)
library(tree)
library(caret)
library(randomForest)
library(gbm)
```

## Not Changing NA/0 Values

```{r data}
set.seed(478)

test <- read.csv("https://raw.githubusercontent.com/trevorisaacson3/KaggleHomePrices/main/test.csv")
train <- read.csv("https://raw.githubusercontent.com/trevorisaacson3/KaggleHomePrices/main/train.csv")

test$SalePrice <- 0

test <- test %>%
  mutate(across(where(is.character), replace_na, "No"), across(where(is.integer), replace_na, 0))

train <- train %>%
  mutate(across(where(is.character), replace_na, "No"), across(where(is.integer), replace_na, 0), SalePrice = log(SalePrice))

ggplot(aes(x = SalePrice), data = train) + 
  geom_histogram()

set.seed(478)
n <- nrow(train)
trn <- sample(seq_len(n), .8*n)
training <- train[trn,]
testing <- train[-trn,]
```

```{r}
dftree <- tree(SalePrice ~ ., training); summary(dftree)
plot(dftree)
text(dftree)
```

```{r}
tree.cv <- cv.tree(dftree)
plot(tree.cv$size, sqrt(tree.cv$dev / nrow(training)), type = "b",
     xlab = "Tree Size", ylab = "CV-RMSE")

tree.prune <- prune.tree(dftree, best = 7); summary(tree.prune)
plot(tree.prune)
text(tree.prune)
title("Pruned Tree")
```

```{r Bagging}
tree <- tree(SalePrice ~ ., data = training); summary(tree) 

tree
plot(tree); text(tree); title("Original Model")
plot(prune.tree(tree))

model.prune <- prune.tree(tree, best = 10); model.prune

plot(model.prune); text(model.prune); title("Pruned Model")
```

```{r}
trm <- cv.tree(tree); 
plot(trm$size, sqrt(trm$dev/nrow(training)))
```

```{r}
pred <- predict(model.prune, testing);

rmse <- sqrt(mean((testing$SalePrice - pred)^2)); rmse
```

```{r}
ggplot(aes(x = as.factor(OverallQual), y = SalePrice), data = training) +
  geom_boxplot()

ggplot(aes(x = GrLivArea, y = SalePrice), data = training) + 
  geom_point()
```

```{r}
newtree <- tree(SalePrice ~ GrLivArea + OverallQual, data = training)
pred <- predict(newtree, testing); 

df <- rbind(as.array(testing$SalePrice), as.array(pred)); 

rmse <- sqrt(mean((testing$SalePrice - pred)^2)); rmse
```

```{r}
newtree2 <- tree(SalePrice ~., data = training)
prune <- prune.tree(newtree2); plot(prune)

newtree2 <- prune.tree(newtree2, best = 8)

pred <- predict(newtree2, testing)

rmse <- sqrt(mean((testing$SalePrice - pred)^2)); rmse
```

```{r}
output <- randomForest(SalePrice ~ ., data = training, mtry = ncol(training)/3, importance = TRUE)

output; which.min(output$mse)
sqrt(output$mse[which.min(output$mse)]) 
varImpPlot(output)
```

```{r}
out_tune <- tuneRF(
  x = training %>% select(-SalePrice),
  y = training$SalePrice,
  ntreeTry = which.min(output$mse),
  mtryStart = ncol(training)/3,
  improve = .01,
  trace = FALSE
)



pred <- predict(output, newdata = testing)

sqrt(mean((testing$SalePrice - pred)^2))
```

## Changing Dataset

```{r}
cond <- (colSums(is.na(test)) < 50) # check categorical variables for NA values
colSums(is.na(test))

df <- test[, cond, drop = TRUE]; df
  
  
cond2 <- colSums(test == 0) # check int variables for values equal to 0
cond2
```
